version: '3.4'

services:
  web:
    image: ${DOCKER_REGISTRY-}hobbystacks-web-spa:${DOCKER_TAG-latest}
    restart: always
    depends_on:
      - api

  api:
    image: ${DOCKER_REGISTRY-}hobbystacks-api:${DOCKER_TAG-latest}
    restart: always
    environment:
      DB_DRIVER: ${DB_DRIVER}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
